baseurl: https://olivroy.netlify.app/
title: Olivier Roy
theme: hugo-theme-console
languageCode: en-us
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
params:
  animateStyle: animated zoomIn fast
  navlinks:
    - name: about/
      url: about/
    - name: posts/
      url: posts/
    - name: photos/
      url: photos/
  titleCutting: yes

markup:
  goldmark:
    renderer:
      unsafe: true
